## Car category classification using Random Forest Classifier

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data=pd.read_csv('data/global_cars_enhanced.csv')
data.head()

,Car_ID,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score
0,CAR_0001,Mercedes,2006,SUV,Petrol,Manual,4089,547,17,73407,USA,20,Premium,0.1338,Old,0.35
1,CAR_0002,Nissan,2023,Coupe,Petrol,Automatic,4618,167,25,79370,USA,3,Premium,0.0362,New,0.75
2,CAR_0003,Nissan,2007,Hatchback,Diesel,Manual,1802,110,16,76549,China,19,Premium,0.0610,Old,0.30
3,CAR_0004,Nissan,2013,Coupe,Petrol,Manual,1835,373,16,48722,USA,13,Mid-Range,0.2033,Old,0.30
4,CAR_0005,Hyundai,2009,Hatchback,Hybrid,Automatic,2332,145,28,83265,UK,17,Premium,0.0622,Old,0.90


In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Car_ID                 300 non-null    str    
 1   Brand                  300 non-null    str    
 2   Manufacture_Year       300 non-null    int64  
 3   Body_Type              300 non-null    str    
 4   Fuel_Type              300 non-null    str    
 5   Transmission           300 non-null    str    
 6   Engine_CC              300 non-null    int64  
 7   Horsepower             300 non-null    int64  
 8   Mileage_km_per_l       300 non-null    int64  
 9   Price_USD              300 non-null    int64  
 10  Manufacturing_Country  300 non-null    str    
 11  Car_Age                300 non-null    int64  
 12  Price_Category         300 non-null    str    
 13  HP_per_CC              300 non-null    float64
 14  Age_Category           300 non-null    str    
 15  Efficiency_Score 

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Car_ID                 300 non-null    str    
 1   Brand                  300 non-null    str    
 2   Manufacture_Year       300 non-null    int64  
 3   Body_Type              300 non-null    str    
 4   Fuel_Type              300 non-null    str    
 5   Transmission           300 non-null    str    
 6   Engine_CC              300 non-null    int64  
 7   Horsepower             300 non-null    int64  
 8   Mileage_km_per_l       300 non-null    int64  
 9   Price_USD              300 non-null    int64  
 10  Manufacturing_Country  300 non-null    str    
 11  Car_Age                300 non-null    int64  
 12  Price_Category         300 non-null    str    
 13  HP_per_CC              300 non-null    float64
 14  Age_Category           300 non-null    str    
 15  Efficiency_Score 

In [6]:
data=data.drop(['Car_ID'], axis=1)

In [7]:
data['Price_Category'].value_counts()

Price_Category
Budget       78
Mid-Range    75
Premium      74
Luxury       73
Name: count, dtype: int64

In [8]:
oe= OrdinalEncoder(categories=[['Budget', 'Mid-Range', 'Premium','Luxury']])
data['Price_Category']=oe.fit_transform(data[['Price_Category']])
data.head()

,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score
0,Mercedes,2006,SUV,Petrol,Manual,4089,547,17,73407,USA,20,2.0,0.1338,Old,0.35
1,Nissan,2023,Coupe,Petrol,Automatic,4618,167,25,79370,USA,3,2.0,0.0362,New,0.75
2,Nissan,2007,Hatchback,Diesel,Manual,1802,110,16,76549,China,19,2.0,0.0610,Old,0.30
3,Nissan,2013,Coupe,Petrol,Manual,1835,373,16,48722,USA,13,1.0,0.2033,Old,0.30
4,Hyundai,2009,Hatchback,Hybrid,Automatic,2332,145,28,83265,UK,17,2.0,0.0622,Old,0.90


In [9]:
le= LabelEncoder()
data['Age_Category']=le.fit_transform(data['Age_Category'])
data.head()

,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score
0,Mercedes,2006,SUV,Petrol,Manual,4089,547,17,73407,USA,20,2.0,0.1338,2,0.35
1,Nissan,2023,Coupe,Petrol,Automatic,4618,167,25,79370,USA,3,2.0,0.0362,1,0.75
2,Nissan,2007,Hatchback,Diesel,Manual,1802,110,16,76549,China,19,2.0,0.0610,2,0.30
3,Nissan,2013,Coupe,Petrol,Manual,1835,373,16,48722,USA,13,1.0,0.2033,2,0.30
4,Hyundai,2009,Hatchback,Hybrid,Automatic,2332,145,28,83265,UK,17,2.0,0.0622,2,0.90


In [10]:
dff= pd.get_dummies(data, dtype=int)
dff.head()

,Manufacture_Year,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score,...,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Manufacturing_Country_China,Manufacturing_Country_Germany,Manufacturing_Country_Japan,Manufacturing_Country_South Korea,Manufacturing_Country_UK,Manufacturing_Country_USA
0,2006,4089,547,17,73407,20,2.0,0.1338,2,0.35,...,0,1,0,1,0,0,0,0,0,1
1,2023,4618,167,25,79370,3,2.0,0.0362,1,0.75,...,0,1,1,0,0,0,0,0,0,1
2,2007,1802,110,16,76549,19,2.0,0.0610,2,0.30,...,0,0,0,1,1,0,0,0,0,0
3,2013,1835,373,16,48722,13,1.0,0.2033,2,0.30,...,0,1,0,1,0,0,0,0,0,1
4,2009,2332,145,28,83265,17,2.0,0.0622,2,0.90,...,1,0,1,0,0,0,0,0,1,0


In [11]:
x=dff.drop('Price_Category', axis=1)
y=dff['Price_Category']
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 36 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Manufacture_Year                   300 non-null    int64  
 1   Engine_CC                          300 non-null    int64  
 2   Horsepower                         300 non-null    int64  
 3   Mileage_km_per_l                   300 non-null    int64  
 4   Price_USD                          300 non-null    int64  
 5   Car_Age                            300 non-null    int64  
 6   HP_per_CC                          300 non-null    float64
 7   Age_Category                       300 non-null    int64  
 8   Efficiency_Score                   300 non-null    float64
 9   Brand_Audi                         300 non-null    int64  
 10  Brand_BMW                          300 non-null    int64  
 11  Brand_Ford                         300 non-null    int64  
 12  Brand

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
xtrain ,xtest,ytrain,ytest= train_test_split(x,y, test_size=0.3, random_state=42)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, precision_score, recall_score

In [15]:
RFCModel=RandomForestClassifier(n_estimators=100, max_depth=5)
RFCModel.fit(xtrain,ytrain)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",5
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric(y_

In [16]:
ypred=RFCModel.predict(xtest)


In [17]:
print('training efficiency:', RFCModel.score(xtrain,ytrain))
print('testing efficiency:', RFCModel.score(xtest, ytest))

training efficiency: 1.0
testing efficiency: 0.9555555555555556


In [18]:
print('confusion_matrix\n', confusion_matrix(ytest, ypred))

confusion_matrix
 [[22  0  0  0]
 [ 0 15  0  0]
 [ 0  2 24  2]
 [ 0  0  0 25]]


In [19]:
print('accuracy_score',accuracy_score(ytest,ypred))
print('precision_score',precision_score(ytest,ypred, average='weighted'))
print('recall_score', recall_score(ytest,ypred, average='weighted'))
print('f1_score', f1_score(ytest,ypred, average='weighted'))

accuracy_score 0.9555555555555556
precision_score 0.9598160251755024
recall_score 0.9555555555555556
f1_score 0.9549679487179488


# car price predicton using Random Forest Regressor


In [20]:
dff.head()

,Manufacture_Year,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score,...,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Manufacturing_Country_China,Manufacturing_Country_Germany,Manufacturing_Country_Japan,Manufacturing_Country_South Korea,Manufacturing_Country_UK,Manufacturing_Country_USA
0,2006,4089,547,17,73407,20,2.0,0.1338,2,0.35,...,0,1,0,1,0,0,0,0,0,1
1,2023,4618,167,25,79370,3,2.0,0.0362,1,0.75,...,0,1,1,0,0,0,0,0,0,1
2,2007,1802,110,16,76549,19,2.0,0.0610,2,0.30,...,0,0,0,1,1,0,0,0,0,0
3,2013,1835,373,16,48722,13,1.0,0.2033,2,0.30,...,0,1,0,1,0,0,0,0,0,1
4,2009,2332,145,28,83265,17,2.0,0.0622,2,0.90,...,1,0,1,0,0,0,0,0,1,0


In [21]:
X=dff.drop('Price_USD', axis=1)
Y= dff['Price_USD']



In [22]:
from sklearn.ensemble import RandomForestRegressor


In [23]:
x_train,x_test,y_train,y_test=train_test_split(X,Y, random_state=42)

In [24]:
RFRmodel=RandomForestRegressor(n_estimators=200, max_depth=5)

In [25]:
RFRmodel.fit(x_train,y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",200
,"criterion criterion: {""squared_error"", ""absolute_error"", ""friedman_mse"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""friedman_mse"", which usesmean squared error with Friedman's improvement score for potentialsplits, ""absolute_error"" for the mean absolute error, which minimizesthe L1 loss using the median of each terminal node, and ""poisson"" whichuses reduction in Poisson deviance to find splits.Training using ""absolute_error"" is significantly slowerthan when using ""squared_error""... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 1.0 Poisson criterion.",'squared_error'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",5
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=1.0The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None or 1.0, then `max_features=n_features`... note:: The default of 1.0 is equivalent to bagged trees and more randomness can be achieved by setting smaller values, e.g. 0.3... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to 1.0.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",1.0
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples a

In [26]:
y_pred=RFRmodel.predict(x_test)

In [27]:
print('training efficiency: ', RFRmodel.score(x_train,y_train))
print('testing efficiency: ', RFRmodel.score(x_test,y_test))

training efficiency:  0.9760288396770177
testing efficiency:  0.9301070898658573
